// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.loansagreements.dao.model.ugoc;

import java.io.Serializable;

privileged aspect FormatoUGFSGOC_Roo_Serializable {
    
    declare parents: FormatoUGFSGOC implements Serializable;
    
    private static final long FormatoUGFSGOC.serialVersionUID = 1L;
    
}
