// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.loansagreements.dao.model.ugoc;

import java.lang.String;

privileged aspect FormatoUGFEGOC_Roo_ToString {
    
    public String FormatoUGFEGOC.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Tipafil: ").append(getTipafil());
        return sb.toString();
    }
    
}
