// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.loansagreements.dao.model.ugoc;

import java.lang.String;

privileged aspect FormatoUGFEGOC_Roo_JavaBean {
    
    public String FormatoUGFEGOC.getTipafil() {
        return this.tipafil;
    }
    
    public void FormatoUGFEGOC.setTipafil(String tipafil) {
        this.tipafil = tipafil;
    }
    
}
