// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.loansagreements.dao.model.ugof;

import java.io.Serializable;

privileged aspect FormatoUGMOFS1_Roo_Serializable {
    
    declare parents: FormatoUGMOFS1 implements Serializable;
    
    private static final long FormatoUGMOFS1.serialVersionUID = 1L;
    
}
