// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.loansagreements.dao.model.ugof;

import java.io.Serializable;

privileged aspect RespuestaTransaccionUgof_Roo_Serializable {
    
    declare parents: RespuestaTransaccionUgof implements Serializable;
    
    private static final long RespuestaTransaccionUgof.serialVersionUID = 1L;
    
}
