// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.loansagreements.dao.model.ugog;

import java.io.Serializable;

privileged aspect RespuestaTransaccionUgog_Roo_Serializable {
    
    declare parents: RespuestaTransaccionUgog implements Serializable;
    
    private static final long RespuestaTransaccionUgog.serialVersionUID = 1L;
    
}
